### ISSUE TITLE
Editor - no style

### ISSUE THREAD

**Issue by NexuS-Pt** [NexuS-Pt/BO2-BOxygen#11]
problem with styling on editor, isn't possiveble see the changes (eg.: bold).

**Comment by NexuS-Pt** [comment]
TAG H2 já disponível.

**Comment by NexuS-Pt** [comment]
BOLD já disponível.

**Comment by NexuS-Pt** [comment]
ITALIC já disponível.

**Comment by NexuS-Pt** [comment]
UNDERLINE já disponível.

**Comment by c42759** [comment]
Novo editor, corrigiu este erro.

CKEditor
